### ISSUE TITLE
收到b站小程序消息时会报错

### ISSUE THREAD

**Issue by yi03** [zhiyu1998/koishi-plugin-r-link-parse#2]
所有插件都是最新版。
在qq里收到b站小程序消息时会报如下的错：
```
2023-05-13 14:38:25 [W] app TypeError: Cannot read properties of null (reading '0')
                            at getVideoInfo (C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-r-link-parse\lib\utils\bilibili-info.js:10:49)
                            at Object.bili [as handler] (C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-r-link-parse\lib\futures\bilibili.js:54:62)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-r-link-parse\lib\index.js:37:22
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-nonebot\lib\internal\matcher.js:183:24
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-who-at-me\lib\index.js:42:16
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-openai-api\lib\index.js:97:20
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
2023-05-13 14:38:25 [E] app TypeError: Cannot read properties of null (reading '0')
                            at getVideoInfo (C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-r-link-parse\lib\utils\bilibili-info.js:10:49)
                            at Object.bili [as handler] (C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-r-link-parse\lib\futures\bilibili.js:54:62)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-r-link-parse\lib\index.js:37:22
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-nonebot\lib\internal\matcher.js:183:24
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-who-at-me\lib\index.js:42:16
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
                            at C:\Users\46589\koishi-bot\koishi-app10\node_modules\koishi-plugin-openai-api\lib\index.js:97:20
                            at next (C:\Users\46589\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:886:69)
```

**Comment by zhiyu1998** [comment]
感谢反馈，实际上我还没有测试小程序，因为我的go-cqhttp用的好像是手表暂时无法测试小程序。

**Comment by Pesafy** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by tgmstudios** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @halicloud, @RandolphJiffy, @tottiss, @oxbigo, @louyongjiu, @tanxu1993, @eth3015, @shawncvv, @MrEasonYang, @hycnbbit, @yisonr, @bai1507, @pandavips, @madao708, @zhangfy1994, @S1mpleLin, @ilovcoding, @hebron666, @Zerocan, @Jcm2046, @Jayden-repo, @TankJam, @smallbearw5251, @lijiehelloworld, @wendell1224, @PandaWuu, @a990215520, @zzllong, @liuyepiaoxiang, @hfme, @lzzsG, @mixbe, @mydanniel, @wgou, @jacksonyoudi, @maczhuo, @zhougx17, @jiangshanmeta, @xiajinchun, @Xh1Xxhg, @shexinyi, @sooody, @albinlau, @yongk513, @yoyoping, @guozqiu, @invisiblecao, @Coderzgh, @lbwxl, @septem776

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by guijunchen** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
xiechuyu, @kevinjoeWang, @darekaze, @alpha731, @ywang1724, @lipengda, @zhou533, @haoziluo, @lyx0723, @flyfire, @qiyiping, @StoolMonster, @caorushizi, @GZ315200, @stone-wind, @lixiangio, @Jcdroid, @wangkaikai12345, @ClayGuitar, @AllenCoder

**Comment by lyx0723** [comment]
您的邮件我已收到，祝您生活愉快！
