### ISSUE TITLE
插件无法正常使用

### ISSUE THREAD

**Issue by loveliveao** [zhiyu1998/koishi-plugin-r-link-parse#5]
# 大佬求求你更新吧！
## 使用Koishi自带的插件商店不能加载此插件，日志中提示无法找到`lodash`模块，日志如下
```
2023-08-26 17:25:50 [W] config failed to load r-link-parse
2023-08-26 17:25:50 [W] config Error: Cannot find module 'lodash'
                        Require stack:
                        - /koishi/node_modules/koishi-plugin-r-link-parse/lib/utils/bilibili-core.js
                        - /koishi/node_modules/koishi-plugin-r-link-parse/lib/futures/bilibili.js
                        - /koishi/node_modules/koishi-plugin-r-link-parse/lib/index.js
                        - /koishi/node_modules/@koishijs/loader/lib/index.js
                        - /koishi/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
                            at Module._load (node:internal/modules/cjs/loader:922:27)
                            at Module.require (node:internal/modules/cjs/loader:1143:19)
                            at require (node:internal/modules/cjs/helpers:121:18)
                            at Object.<anonymous> (/koishi/node_modules/koishi-plugin-r-link-parse/lib/utils/bilibili-core.js:11:34)
                            at Module._compile (node:internal/modules/cjs/loader:1256:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
                            at Module.load (node:internal/modules/cjs/loader:1119:32)
                            at Module._load (node:internal/modules/cjs/loader:960:12)
                            at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-08-26 17:25:56 [I] app apply plugin r-link-parse:3g8ypq
2023-08-26 17:25:56 [E] loader Error: Cannot find module 'lodash'
                        Require stack:
                        - /koishi/node_modules/koishi-plugin-r-link-parse/lib/utils/bilibili-core.js
                        - /koishi/node_modules/koishi-plugin-r-link-parse/lib/futures/bilibili.js
                        - /koishi/node_modules/koishi-plugin-r-link-parse/lib/index.js
                        - /koishi/node_modules/@koishijs/loader/lib/index.js
                        - /koishi/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
                            at Module._load (node:internal/modules/cjs/loader:922:27)
                            at Module.require (node:internal/modules/cjs/loader:1143:19)
                            at require (node:internal/modules/cjs/helpers:121:18)
                            at Object.<anonymous> (/koishi/node_modules/koishi-plugin-r-link-parse/lib/utils/bilibili-core.js:11:34)
                            at Module._compile (node:internal/modules/cjs/loader:1256:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
                            at Module.load (node:internal/modules/cjs/loader:1119:32)
                            at Module._load (node:internal/modules/cjs/loader:960:12)
                            at Module.require (node:internal/modules/cjs/loader:1143:19)
```
## 尝试使用控制台通过npm安装`lodash`依赖后可让插件运行，但无法正常实现功能。
```
2023-08-26 17:45:35 [I] gocqhttp-dev 收到群 动力牛子(781806489) 内 群原皮 不水群的时候都在工作(1057005944) 的消息: 【“电脑工作者，这把人体工学键盘一定要试一试”-哔哩哔哩】 https://b23.tv/nhINjW0 (1138660980)
2023-08-26 17:45:37 [W] gocqhttp-dev 转换消息 [CQ:video,file=file:////koishi/node_modules/koishi-plugin-r-link-parse/lib/constant/../tmp/1057005944/temp.mp4,cache=0] 到MiraiGo Element时出现错误: file not found.
2023-08-26 17:45:37 [I] gocqhttp-dev 转换消息 [CQ:video,file=file:////koishi/node_modules/koishi-plugin-r-link-parse/lib/constant/../tmp/1057005944/temp.mp4,cache=0] 到MiraiGo Element时出现错误: file not found.
2023-08-26 17:45:38 [I] gocqhttp-dev 发送群 动力牛子(781806489) 的消息: [{"type":" ... (886679266)
2023-08-26 17:45:40 [I] gocqhttp-dev 发送群 动力牛子(781806489) 的消息: [{"type":" ... (1411264263)
```
### One more thing
跪求大佬抽空更新！！！
从云崽那边接触到你的插件后就一直在用这个插件，得知大佬转到Nonebot和Koishi并不再维护云崽的消息时毅然决然配置了Nonebot和Koishi。但是发现这两个平台的插件都无法正常运行，真的感觉到很可惜。
如果大佬能看到这个issue，希望在有精力的前提下维护一下这个插件。
最后祝您万事顺遂，平安喜乐！

**Comment by YipSzeho** [comment]
同求大佬更新(*'へ'*)
